apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-ci
spec:
  serviceAccountName: jenkins

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  containers:
    - name: ci
      image: localhost:32000/python-ci:lab
      imagePullPolicy: IfNotPresent

      command:
        - cat
      tty: true

      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

  restartPolicy: Never